qr_encoder/main/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    SubmitField
)
from wtforms.validators import (
    InputRequired,
    URL
)


class QRForm(FlaskForm):
    url = StringField('Input a URL:',
        validators=[InputRequired(), URL(
                    require_tld=True,
                    message='<h3>URL not valid!</h3><p>Be sure to prefix the appropriate protocol.<br>(HTTP:// | HTTPS:// | FTP:// | etc)</p>')],
        render_kw={"id": "url",
                   'class': 'uk-input uk-form-large uk-border-pill',
                   "placeholder": "https://example.com"})

    submit = SubmitField('Generate QR Code', render_kw={
                        'id': 'submit',
                        'class': 'uk-button uk-button-primary uk-border-pill uk-width-1-1'})

qr_encoder/__init__.py
from flask import Flask, abort
from flask_wtf.csrf import CSRFProtect
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

from qr_encoder.config import ProductionConfig

'''
    APP CONFIG
'''

csrf = CSRFProtect()
limiter = Limiter(
    get_remote_address,
    default_limits=["50 per day", "10 per hour"],
    storage_uri="memory://",
)

def create_app():
    app = Flask(__name__)
    app.config.from_object(ProductionConfig)

    if not app.secret_key:
        raise ValueError("No SECRET_KEY set for Flask application")
        abort(500)

    csrf.init_app(app)
    limiter.init_app(app)

    from qr_encoder.main.routes import main
    app.register_blueprint(main)

    return app

qr_encoder/main/routes.py
from flask import render_template, request, jsonify, Blueprint
import io
from base64 import b64encode
from datetime import datetime
import qrcode
from qr_encoder.main.forms import QRForm

main = Blueprint('main', __name__)


@main.context_processor
def inject_year():
    year = datetime.now().year
    return dict(current_year=year)

@main.context_processor
def inject_year():
    app_name = "QR Encoder"
    return dict(app_name=app_name)


def process_qr(url):
    img_io = io.BytesIO()
    qr = qrcode.make(url)
    qr.save(img_io)
    img_io.seek(0)
    encoded_img_data = b64encode(img_io.getvalue())
    encoded_img_data = encoded_img_data.decode('utf-8')
    return encoded_img_data


@main.route('/', methods=['GET', 'POST'])
def index():
    form = QRForm()
    if form.validate_on_submit():
        url = form.url.data
        qr_code = process_qr(url)
        qr_code = 'data:image/png;base64,{}'.format(qr_code)
        data = {
            'url': url,
            'qr_code': qr_code
        }
        # add to database
        # ...
        return jsonify(data)
    if request.method == 'POST':
        errors = form.errors
        qr_code = '/static/images/qr-placeholder.png'
        data = {
            'errors': errors['url'],
            'qr_code': qr_code
        }
        return jsonify(data)

    return render_template('index.html', form=form)

qr_encoder/templates/index.html
{% extends 'layouts/base.html' %}

{% block body %}

<!-- Intro -->
<div class="uk-section uk-section-default uk-section-small" id="intro">
    <div class="uk-container">

        <!-- logo -->
        <div class="uk-width-1-1">
            <div class="title">Website to QR code converter</div>
            <div class="sub">Convert a website URL to a scannable QR code.</div>
        </div>

    </div>
</div>
<!-- / Intro -->




<section class="uk-section uk-section-default">
    <div class="uk-container">

        <div class="" uk-grid>

            <div class="uk-width-1-1@s uk-width-3-5@m">
                <div class="uk-card uk-card-default uk-card-body">

                    <h3 class="">Generate a QR code <span class="uk-clearfix"><a href="#help-modal" class="uk-float-right uk-icon-button help-button uk-animation-slide-right" uk-icon="icon: question" uk-toggle></a></span></h3>

                    <!-- Form -->
                    <form id="qr-form" action="{{ url_for('main.index') }}" method="post">
                        {{ form.csrf_token }}

                        <fieldset class="uk-fieldset">

                            <div class="uk-margin">
                                {{ form.url.label(class="uk-form-label") }}
                                {{ form.url }}
                            </div>

                            {{ form.submit }}

                        </fieldset>

                        {% if form.url.errors %}
                        <div class="uk-alert-danger" uk-alert>
                            <p>{{ form.url.errors[0] }}</p>
                        </div>
                        {% endif %}

                    </form>
                    <!-- / Form -->

                </div>
            </div>

            <div class="uk-width-1-1@s uk-width-2-5@m">
                <div id="borderpop" class="uk-card uk-card-default uk-card-body uk-flex uk-flex-center uk-flex-middle uk-text-center">

                    <div id="arcaloader" style="display: none;" class="uk-cover-container">
                        <img src="{{ url_for('static', filename='images/loader.gif') }}" alt="Loading...">
                    </div>

                    <div id="result" class="uk-text-default">
                        <div>
                            <a href="https://ArcaneSolutions.io" target="_blank">https://ArcaneSolutions.io</a>
                            <img class="qr-placeholder" id="picture" src="{{ url_for('static', filename='images/qr-placeholder.png') }}" alt="https://ArcaneSolutions.io">
                        </div>
                    </div>

                </div>
            </div>

        </div>

    </div>
</section>

<!-- Overview Section -->
<section class="uk-section uk-section-default">
    <div class="uk-container">

        <h2 class="uk-heading-line uk-text-center"><span>Why Choose QRCode Monkey?</span></h2>

        <div class="uk-grid-match uk-child-width-1-1@s uk-child-width-1-2@m" uk-grid>
            <div>
                <p>Unlimited lifetime and scanning without limits await with QRCode Monkey. Unlike other QR code generators that have restrictions and expirations, our QR codes are forever functional and have no limitations on scans. Although the QR codes are static, you can add a custom logo with an error correction rate of up to 30%.</p>

                <p>Make your QR code stand out with our customization options. Choose from different designs, shapes, and colors to create a truly unique QR code. Adding attractive colors and gradients can increase the number of scans.</p>
            </div>
            
            <div>
                <p>QRCode Monkey offers high-resolution QR codes suitable for printing. You can create .png files in print quality by setting the pixel size to the highest resolution. We also provide vector formats like .svg, .eps, and .pdf for the best possible quality. The .svg format is recommended because it retains all design settings and is compatible with most vector graphic software.</p>

                <p>Unlike other free QR code makers that only allow low-resolution codes, we offer vector formats that support huge resolutions without losing quality. The .svg format is ideal for further editing. The .pdf and .eps formats only support classic QR codes without customization options.</p>

                <p>All QR codes generated by QRCode Monkey are 100% free for commercial use, so you can use them for any purpose without restrictions.</p>
            </div>
        </div>

    </div>
</section>
<!-- Overview section -->

<!-- HELP MODAL -->
<div id="help-modal" class="uk-flex-top" uk-modal>
    <div class="uk-modal-dialog uk-modal-body help-modal uk-margin-auto-vertical">

        <button class="uk-modal-close-default" type="button" uk-close></button>

            <h3>Help Panel</h3>
            <dl class="uk-description-list uk-text-warning">
                <dt>URL Requirements:</dt>
                <dd>- Prefix the appropriate protocol [HTTP:// | HTTPS:// | FTP:// | etc]</dd>
                <dd>- Include a TLD [.COM | .ORG | .IO | etc]</dd>
            </dl>

    </div>
</div>
{% endblock %}

qr_encoder/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, shrink-to-fit=no, width=device-width">
    <title>{% block title %}QR Encoder{% endblock %}</title>
    <meta name="author" content="Arcane Solutions">
    <meta name="description" content="URL to QR encoder. Covert a website link to a QR image.">
    <meta name="keywords" content="qr code converter, qr code encoder, qr ..., arcane solutions">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='images/favicon.png') }}">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/uikit.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">

    <script src="https://www.unpkg.com/jquery@3.6.4/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">

    <!-- Additional/Super CSS -->
    {% block moreStyles %}{% endblock moreStyles %}
  </head>
  <body>

    {% include 'layouts/header.html' %}

    <!-- Main body -->
    <div class="main-body" role="main">
      {% block body %}{% endblock %}
    </div>
    <!-- /  Main body -->

    {% include 'layouts/footer.html' %}

    <!-- Scripts -->
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    <script src="{{ url_for('static', filename='js/uikit.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/uikit-icons.min.js') }}"></script>

    <!-- Additional/Super CSS -->
    {% block moreScripts %}{% endblock moreScripts %}

  </body>
</html>

qr_encoder/templates/layouts/footer.html
<!--FOOTER-->
<footer class="uk-section-secondary">
    <div class="uk-section uk-section-xsmall" style="background-color: rgba(0,0,0,100)">
        <div class="uk-container">
            <div class="uk-grid uk-child-width-1-2@s uk-text-center uk-text-left@s" data-uk-grid>
                <div class="uk-text-small uk-text-muted">
                    {{ current_year }} - Created by <a href="https://ev0x.com" target="_blank">ev0x</a> @ <a href="https://arcanesolutions.io" target="_blank">Arcane Solutions</a>
                </div>
                <div class="uk-text-small uk-text-muted uk-text-right@s">
                    <a href="{{ url_for('main.index') }}" target="_blank">{{ app_name }}</a>
                    <a href="https://arcanesolutions.io" target="_blank"><img class="arcane-solutions" src="{{ url_for('static', filename='images/arcane-solution.svg') }}" alt=""></a>
                </div>
            </div>
        </div>
    </div>
</footer>
<!--/FOOTER-->

qr_encoder/templates/layouts/header.html
<!--HEADER-->
<header class="uk-box-shadow-small" style="background-color: white">
    <div class="uk-container">

        <nav class="uk-navbar" id="navbar" data-uk-navbar>
            <div class="uk-navbar-left">
                <a class="uk-navbar-item uk-logo" href="{{ url_for('main.index') }}">QR Encoder</a>
            </div>

            <div class="uk-navbar-right">
                <ul class="uk-navbar-nav">
                    <li class="{% if request.path == '/' %} uk-active {% endif %}"><a href="{{ url_for('main.index') }}">Home</a></li>
                </ul>
            </div>
        </nav>

    </div>
</header>
<!--/HEADER-->